ad `create package` action

diff --git a/splinter b/splinter
--- a/splinter
+++ b/splinter
@@ -140,40 +140,46 @@ printf  "usage: %s [option] action [object] [settings]\n" "$my_name"
 cat << 'EOF'
 
 options:
-       -e|--env conda|pyenv     List available profiles
-       --help                   Print help\
-       --version                Print Splinter version and release date
+       -e|--env conda|pyenv      List available profiles
+       --help                    Print help\
+       --version                 Print Splinter version and release date
 
 actions:
-       list profiles            List available profiles
-       provision [settings]     Provision the host\
-       update <object>          Update the object
+       create package [settings] Create distributable package of your splinter project
+       list profiles             List available profiles
+       provision [settings]      Provision the host\
+       update <object>           Update the object
 
 obejcts:
-       conda                    Reinstall the most recent Miniconda Python environment available for splinter
-       pyenv                    Reinstall Pyenv Python environment
-       galaxy|galaxy-roles      Force update all the Ansible Galaxy roles
-       tools                    Update the splinter tools
-       deps|dependencies        Update all the dependencies (Python envs and  Ansible Galaxy role)
-       self|auto|splinter       Update Splinter itself (but not the tools or dependencies)
-       profiles [settings]      Update the profiles from a online git repo (for now only github is supported)
+       conda                     Reinstall the most recent Miniconda Python environment available for splinter
+       pyenv                     Reinstall Pyenv Python environment
+       galaxy|galaxy-roles       Force update all the Ansible Galaxy roles
+       tools                     Update the splinter tools
+       deps|dependencies         Update all the dependencies (Python envs and  Ansible Galaxy role)
+       self|auto|splinter        Update Splinter itself (but not the tools or dependencies)
+       profiles [settings]       Update the profiles from a online git repo (for now only github is supported)
 
 settings:
        [ provision ]
-       -c file                  Specify a custom configuration file
-       -u username              New user username (all lowercase  without spaces)
-       -f 'Full Name'           New user full name (quoted if has blank spaces)
-       -p 'cleartext password'  New user's password in cleartext (quoted if has blank spaces)
-       -t username              Target user username, if different than the new user (can be used to provision the current account)
-       -h Computer-Name         Computer host name no blank spaces allowed
-       -q                       Suppress all non-Ansible output (except errors and warnings), is overriden with '-v'
-       -v                       Produce verbose output
+       -c file                    Specify a custom configuration file
+       -u username                New user username (all lowercase  without spaces)
+       -f 'Full Name'             New user full name (quoted if has blank spaces)
+       -p 'cleartext password'    New user's password in cleartext (quoted if has blank spaces)
+       -t username                Target user username, if different than the new user (can be used to provision the current account)
+       -h Computer-Name           Computer host name no blank spaces allowed
+       -q                         Suppress all non-Ansible output (except errors and warnings), is overriden with '-v'
+       -v                         Produce verbose output
 
        [ provision, update profiles ]
-       -a account_name          Specify the the Github account name for the custom `splinter-profiles` repo
-       -g git-repo-name         Specify the the Github repository name for the custom `splinter-profiles` repo
-       -b profile_name          Specify the the BASE profile to be used (default: 'default')
-       -r profile_name          Specify the the ROLE profile to be used
+       -a account_name            Specify the the Github account name for the custom `splinter-profiles` repo
+       -g git-repo-name           Specify the the Github repository name for the custom `splinter-profiles` repo
+       -b profile_name            Specify the the BASE profile to be used (default: 'default')
+       -r profile_name            Specify the the ROLE profile to be used
+
+       [ create package ]
+       -n Package-Name            The name of the package (without extension)
+       -d directory_path          The destination directory where to place the package
+       -t dmg|zip                 The type of package
 
 EOF
   printf  "Create your own profiles in the '%s' directory.\n" "$profiles_path"
@@ -193,6 +199,7 @@ function locate_config_file {
       else
         # assumes the directory that contains the `splinter` script is the Splinter directory
         splinter_config_file_dir="$(abs_path "$(dirname "$0")")"
+        splinter_config_file_dir="${splinter_config_file_dir%"/."}" # remove training '/.' if any
       fi
       splinter_config_file="${splinter_config_file_dir}/${splinter_config_file}"
     fi
@@ -243,6 +250,7 @@ function export_ansible_envs {
 
 function show_envs {
   _echo "$(eval show_version)"
+  _echo "action: $action $action_option"
   _echo "VERBOSE: $VERBOSE"
   [[ -n $SPLINTER_PROJECT_DIR ]]          && _echo "SPLINTER_PROJECT_DIR: $SPLINTER_PROJECT_DIR"
   [[ -n $splinter_config_file ]]         && _echo "SPLINTER_CONFIG_FILE: $splinter_config_file"
@@ -309,9 +317,11 @@ function set_app_directories {
 }
 
 function update_splinter {
-  _echo "Updating splinter" 'a'
-  splinter_archive="${my_name}.zip"
+  local temp_dir
   temp_dir=$(mktemp -d)
+  splinter_archive="${my_name}.zip"
+
+  _echo "Updating splinter" 'a'
 
   _echo "Downloading Splinter into '${temp_dir}/${splinter_archive}'" 'a'
   _exec "curl" "-fsSL" "$splinter_archive_url" "-o" "${temp_dir}/${splinter_archive}"
@@ -414,6 +424,92 @@ function update_profiles {
   _exec "rm" "-rf" "$temp_dir"
 
   _echo "Profiles updated successfully!" 'r'
+}
+
+function create_package {
+  local temp_dir
+  local project_dir_number_of_files
+  local rsync_failed
+  local source_dir
+
+  [[ $package_type == "" ]] && package_type="dmg"
+  [[ $package_name == "" ]] && package_name="SplinterProvision"
+  [[ $package_destination == "" ]] && package_destination="$project_dir"
+
+  if [[ ! -d $package_destination ]]; then
+    _echo "Cannot find the destination directory '$package_destination'" 'e'
+    exit 1
+  fi
+
+  local package_output="${package_destination}/${package_name}.${package_type}"
+
+  if [[ -f $package_output ]]; then
+    _echo "The package '$package_output' already exists" 'e'
+    _echo "Delete the old package before proceeding" 'e'
+    exit 1
+  fi
+
+  [[ -n $SPLINTER_BASE_PROFILE ]] && eval retrieve_profile "$SPLINTER_BASE_PROFILE"
+  [[ -n $SPLINTER_ROLE_PROFILE ]] && eval retrieve_profile "$SPLINTER_ROLE_PROFILE"
+  eval install_dependencies
+
+  project_dir_number_of_files=$(find "$project_dir" -not -name ".gitignore" -not -path '*/\.git*' -not -name "*.dmg" -not -name "*.zip" -not -name ".DS_Store" |wc -l)
+  temp_dir=$(mktemp -d)
+
+  [[ $package_type != "" ]] && _echo "package_type: $package_type"
+  [[ $package_name != "" ]] && _echo "package_name: $package_name"
+  [[ $package_destination != "" ]] && _echo "package_destination: $package_destination"
+
+  source_dir="${temp_dir}/${package_name}"
+  _echo "TEMP_DIR: $source_dir"
+  mkdir -p "$source_dir"
+
+  _echo "Copying the project files into the temporary directory" 'a'
+  rsync -rlWuv \
+        --exclude ".git" \
+        --exclude ".gitignore" \
+        --exclude ".DS_Store" \
+        "$project_dir"/* \
+        "$source_dir" | pv -ples "$project_dir_number_of_files"  > /dev/null || rsync_failed="true"
+
+  [[ $rsync_failed == "true" ]] && _echo "Copying the project files failed" 'e' && exit 1
+
+  eval bundle_package "$package_type" "$source_dir" "$package_output"
+
+  _echo "Removing temporary files" 'a'
+  _exec "rm" "-rf" "$temp_dir"
+  _echo "Archive '$package_output' created successfully" 'r'
+}
+
+function bundle_package {
+  if [[ "$1" == "" || "$2" == "" || "$2" == "" ]]; then
+    echo "'bundle_package' called with not enough parameters"
+    exit
+  fi
+
+  local package_type="$1"
+  local source_dir="$2"
+  local package_output="$3"
+  local source_project_dir
+
+  source_dir_number_of_files=$(find "$source_dir" | wc -l)
+  source_project_dir=${source_dir%%+(/)}    # trim however many trailing slashes exist
+  source_project_dir=${source_project_dir##*/}       # remove everything before the last / that still remains
+
+  case $package_type in
+    zip)
+      _echo "Creting the ZIP package '$package_output'" 'a'
+      _exec "cd" "${source_dir}/.."
+      zip -r --symlinks \
+          -X "$package_output" \
+          "$source_project_dir" |  pv -ples "$source_dir_number_of_files"  > /dev/null || zipping_failed="true"
+      [[ $zipping_failed == "true" ]] && _echo "Zipping the project files failed" 'e' && exit 1
+    ;;
+    dmg|*)
+      _echo "Creating the Disk Image '$package_output'" 'a'
+      _exec "hdiutil" "create" "$package_output" "-ov" "-volname" "package_name" "-fs" "HFS+" "-srcfolder" "$source_dir"
+    ;;
+  esac
 }
 
 function check_install_path_permissions {
@@ -738,7 +834,6 @@ function install_dependencies {
 }
 
 function provision {
-  _echo "$(eval show_version)"
   _echo "Starting time $( date )" 'r'
   eval ask_for_ansible_sudo_password
   eval enable_passwordless_sudo
@@ -864,6 +959,60 @@ function action_update {
   esac
 }
 
+function action_create {
+  action_option="$1"; # fetch the action's option
+  case $action_option in
+    package)
+      shift
+      action_message="Will create a provisioning package"
+      while getopts ":d:n:t:" create_setting; do
+        case $create_setting in
+          d)
+            package_destination="${OPTARG}"
+            ;;
+          n)
+            package_name="${OPTARG}"
+            ;;
+          t)
+            package_type="${OPTARG}"
+            ;;
+          \?)
+            echo "[Error] Action '$action $action_option': Invalid setting '-${OPTARG}'" 1>&2
+            eval show_usage 1>&2
+            exit 1
+            ;;
+          :)
+            echo "[Error] Action '$action $action_option': setting '-${OPTARG}' is missing an argument" 1>&2
+            eval show_usage 1>&2
+            exit 1
+            ;;
+        esac
+      done
+
+      shift $(( OPTIND - 1 ))
+
+      if [[ -n $* ]];then
+        # if it is NOT empty it means it interrupted before evaluating all the parameters
+        # becaue it encountered a unexpected param or arg
+        echo "[Error] Provided unknow parameter: $1" 1>&2
+        eval show_usage 1>&2
+        exit 1
+      fi
+      ;;
+    '')
+      echo "[Error] Missing option for action '$action'" 1>&2
+      eval show_usage 1>&2
+      exit 1
+      ;;
+    *)
+      echo "[Error] Incorrect option '$action_option' for action '$action'" 1>&2
+      eval show_usage 1>&2
+      exit 1
+      ;;
+  esac
+  action_requested="create_package"
+}
+
 function action_provision {
   while getopts ":a:c:b:f:g:h:p:r:t:u:qv" action_setting; do
     case "$action_setting" in
@@ -952,6 +1101,10 @@ function main {
 
   action="$1"; shift
   case "$action" in
+    create)
+      verbose='yes' # `create` will always be verbose
+      eval action_create "$@"
+      ;;
     list)
       eval action_list "$1"
       ;;
@@ -976,7 +1129,6 @@ function main {
 
   eval setup_environment
   [[ $quiet == 'no' ]] && eval show_title
-  _echo "action: $action $action_option"
   eval show_envs
   [[ -n $action_message ]] && _echo "$action_message" 'w'
   [[ -n $action_requested ]] && eval "$action_requested" "$action_requested_options"
